### ISSUE TITLE
[Question] Does it update `Resource.Designer.cs`?

### ISSUE THREAD

**Issue by htcfreek** [8LWXpg/vscode-resx#1]
Does it only edit resx code or does it also updates `Resource.Designer.cs`?

**Comment by 8LWXpg** [comment]
No, it only acts as a simple text editor so far.

**Comment by htcfreek** [comment]
Thank you for the answer.

**Comment by 8LWXpg** [comment]
@htcfreek I wrote the generator for `Resource.Designer.cs` and it's now available at version 1.0.0. Should work for most cases, feel free to give any feed back!
